connector.name=sqlserver

connection-url=jdbc:sqlserver://${ENV:MSSQL_HOST}:1433;databaseName=${ENV:MSSQL_DATABASE};encrypt=true;trustServerCertificate=true

connection-user=${ENV:MSSQL_USER}

connection-password=${ENV:MSSQL_PASSWORD}
