connector.name=redshift

connection-url=jdbc:redshift://${ENV:REDSHIFT_CLUSTER}:${ENV:REDSHIFT_PORT}/${ENV:REDSHIFT_DATABASE}

connection-user=${ENV:REDSHIFT_POSIND_KURLOG_USER}

connection-password=${ENV:REDSHIFT_POSIND_KURLOG_PASSWORD}
